server:
  port: 10002


spring:
  application:
    name: config-ssm

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: root
    password: 123456
    url: jdbc:mysql://localhost:3306/car?serverTimezone=UTC;


mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:mapping/*.xml
